export const FAL_COST_PER_1K_CHARACTERS_USD = 0.15;
export const CUSTOM_VOICE_TEXT_COST_PER_1K_CHARACTERS_USD = 0.1;
export const CUSTOM_VOICE_TRANSFORM_COST_PER_MINUTE_USD = 0.12;
export const THREEZINC_MARKUP_MULTIPLIER = 1.25;
export const THREEZINC_CREDITS_PER_USD = 20;
export const MINIMUM_THREEZINC_CREDITS = 0.5;
export const THREEZINC_CREDIT_INCREMENT = 0.5;
