import type { SharedVoiceSummary } from "@/lib/elevenlabs";

export const SEEDED_SHARED_VOICES = [
  {
    "publicOwnerId": "f87f057c2250691953ac2e6227859706764bd08c88a055a18c74261957885a51",
    "voiceId": "d0grukerEzs069eKIauC",
    "name": "Ranga - Powerful Brand Hindi Narrator",
    "description": "Ranga delivers a deep, authoritative, and energetic tone that commands attention from the first word. His strong vocal presence makes content feel impactful, confident, and driven while maintaining clarity and control. Ideal for promos, brand videos, motivational content, powerful storytelling, commentary, and high-energy narration. Well-suited for media, advertising, digital content, and projects that require a bold and commanding voice presence.",
    "accent": "standard",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/514d94e9241c48e8b7905375729c436f/voices/d0grukerEzs069eKIauC/Xz8cDY03GJAbZHxc4QVX.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "LHJy3mhZWsvhUjy0zUM1",
    "name": "Amrut Deshmukh - Educational Hindi Voice",
    "description": "Amrut Deshmukh delivers a clear, articulate, and engaging Hindi tone designed for educational content. His structured and easy-to-follow delivery makes complex ideas feel simple and accessible, keeping learners attentive throughout. Ideal for explainers, learning videos, courses, concept breakdowns, and knowledge-driven content. Well-suited for edtech platforms, education channels, competitive exam prep, and informational content focused on clarity and understanding.",
    "accent": "standard",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "informative_educational",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/LHJy3mhZWsvhUjy0zUM1/UnfRkMpKLcUXN4WChk1Z.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "zMndFmtlJvAIQjxXWZTU",
    "name": "Shanaya - Respectful Hindi Survey Caller",
    "description": "Shanaya makes customers feel like their opinion genuinely matters. Sweet, respectful, and naturally engaging \u2014 her tone creates the kind of comfortable space where honest feedback flows without hesitation. Built for post-call surveys, NPS collection, product feedback flows, and customer experience research where warmth drives response quality. Ideal for e-commerce brands, telecom providers, healthcare platforms, banking services, and any business that wants every feedback interaction to feel like a conversation, not a questionnaire.",
    "accent": "standard",
    "gender": "male",
    "age": "young",
    "useCase": "conversational",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/zMndFmtlJvAIQjxXWZTU/0R2q5qqaoVtVZRE80J4I.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "41GfRGR5eeQ7QaI6290n",
    "name": "Shera \u2013 Accented Hindi Recovery Agent",
    "description": "Shera delivers a composed, formal tone built for high-accountability recovery environments. Her calm, professional delivery carries the authority of corporate banking without aggression \u2014 ideal for first party collections, regulated payment follow-ups, formal demand outreach, and compliance-driven recovery workflows. A strong fit for banks, NBFCs, insurance companies, ARCs, and fintech platforms operating under strict regulatory frameworks where tone and precision both matter.",
    "accent": "standard",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "conversational",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/41GfRGR5eeQ7QaI6290n/79WiWxiPKH0GTYrSI3P9.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "6fd3438cdf34cd2cc8e2ef6f0d3bf7149d5a5c1606fb7f3069454edd279a1ad8",
    "voiceId": "2cdvnKJ5TZi631y5PN1s",
    "name": "Rahul S \u2013 Professional Hindi Conversational Voice",
    "description": "A natural, clear, and conversational Hindi voice designed for real-world AI applications.\n\nSuitable for assistants, customer interactions, storytelling, and everyday communication, this voice maintains a calm, balanced tone with subtle warmth.\n\nBuilt with a focus on clarity, consistency, and natural flow, it adapts well across both structured and free-flowing conversations.",
    "accent": "standard",
    "gender": "male",
    "age": "young",
    "useCase": "conversational",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/49bd6dfdb0d4421ea576d1ae6f24b2bd/voices/2cdvnKJ5TZi631y5PN1s/bDDfPYp5k0XaVWzPug6G.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "tA6LGZpsqStKtSaGiXND",
    "name": "Tara \u2013 Hindi Reels Explainer Style",
    "description": "Tara delivers clear, engaging, and easy-to-follow Hindi explanations designed for social media videos. Her delivery keeps information simple, structured, and listener-friendly, making complex topics easy to understand quickly. A well-known voice on the voice library, her profiles have generated over 600 million characters, reflecting strong creator trust. Ideal for Instagram Reels, YouTube Shorts, and Hindi-first digital campaigns.",
    "accent": "standard",
    "gender": "female",
    "age": "young",
    "useCase": "social_media",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/tA6LGZpsqStKtSaGiXND/3asIejxY5mWvaSh3kHvu.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "b239f2c890f4672b45523df6b222832e59721df73ea8195b5280d0f0b5e0eb5f",
    "voiceId": "bpkHhw4QrZFYIfahwsHh",
    "name": "Amit Bhawani - Calm Hindi Voice",
    "description": "A professional Voice for your Podcast, TED Talk or Insta Reels.",
    "accent": "gujarati",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "informative_educational",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/user/wPDqj8kocSVAPAUQZhwgkRpU8r83/voices/bpkHhw4QrZFYIfahwsHh/9dd48255-51f7-446b-86ed-54bf4e6f154e.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "662f38325d09c7574de0d4c40239cd7508fb7f87d841588852b89f9e845c6df7",
    "voiceId": "ORVNcvnT1UwPA7XQ29WD",
    "name": "Kuber J - Bold Energetic Hindi Narrator",
    "description": "Energetic & Clear Hindi Narrator - With his youthful energy and strong command of language, Kuber J is an ideal choice for a wide range of applications, including social media content, educational videos, corporate presentations, and more.",
    "accent": "standard",
    "gender": "male",
    "age": "young",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/user/vRtu6takCOZSURkgtdkCBMJ1Vnf2/voices/ORVNcvnT1UwPA7XQ29WD/eb215aef-6011-4842-8154-668e44728179.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "96cf8ff549b1d0b45ef2a353616692cff80ffa0f472b20a1c8ee834db99afca0",
    "voiceId": "qsz5tTEjPvsiIJZIpM8S",
    "name": "Kamal - Hindi calm narrator ",
    "description": "Calm, clear Hindi narrator. Perfect for stories, videos, education, and motivational content.",
    "accent": "standard",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/2463c5b402e5482699858f8d3a065e63/voices/qsz5tTEjPvsiIJZIpM8S/ac27d242-1c9b-4e6a-b68e-36dd808d8bfd.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "XNJDyPyJ8r4J7de0WJwB",
    "name": "Sudhir - Warm & Expressive Hindi Voice",
    "description": "Engaging, deeply expressive, and rooted in rich, natural Hindi, Sudhir brings a warm, middle-aged storytelling presence that makes every narrative feel lived-in and genuinely felt. His audiobook-friendly delivery flows effortlessly between emotion and clarity, keeping listeners absorbed from the very first word. Built for Hindi audiobooks, fiction narration, short story content, and long-form storytelling. Ideal for audio platforms, regional fiction platforms, and content creators.",
    "accent": "standard",
    "gender": "male",
    "age": "young",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/XNJDyPyJ8r4J7de0WJwB/SYGoKPThN1wD0tdP4MBC.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "f87f057c2250691953ac2e6227859706764bd08c88a055a18c74261957885a51",
    "voiceId": "JTPrASXyK62cF3L7w8hv",
    "name": "P K Anil - Clear and Neutral Hindi",
    "description": "P K Anil - Clear Hindi - P.K. Anil Kumar is a veteran in the ad industry and has a great command of the Hindi language. Voice is exciting, energetic, and full of clear Hindi pronunciation. Suitable for conversations.",
    "accent": "standard",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "conversational",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/514d94e9241c48e8b7905375729c436f/voices/JTPrASXyK62cF3L7w8hv/QTUXNgHCJnjO3JLOTTZI.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "9d568089e7d2ef03147e942cfa29577d3be7ef67856f4074ed207f910a48f29d",
    "voiceId": "7wlfJf72PCt9FjPj0Beg",
    "name": "Nishi - Hindi-English & Storytelling ",
    "description": "This voice sample showcases a versatile bilingual (Hindi + English) voice with a wide expressive range. It includes storytelling, enthusiastic narration, reel-style voiceovers, social messaging tones, meditative and calming delivery, empowering and motivational segments, as well as emotional variations such as sad, worried, happy, startled, and scared. The overall voice quality is warm, expressive, and pleasing, suitable for positive, motivational, narrative, and character-driven content.",
    "accent": "indian",
    "gender": "female",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/user/dE86yiRIhRS9TM1ZQRxtQ3YYoQS2/voices/7wlfJf72PCt9FjPj0Beg/OWPH9tP9haMBWbjvYMwX.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "YIXhzp6l2M0ddzOGIbJ3",
    "name": "Tashi \u2013 Expressive Hindi Kids Narrator",
    "description": "Tashi \u2013 Bright & Dramatic Tone - Tashi\u2019s voice is playful, melodious, and full of animated expressions \u2014 designed to bring children\u2019s stories and characters to life.\n\nWith a naturally dramatic and engaging tone, it\u2019s ideal for holding young listeners\u2019 attention.\n\nPerfect for animated videos, moral stories, e-learning content, and children\u2019s podcasts. Also suitable for voiceovers in story apps, nursery rhymes, and early education platforms.",
    "accent": "indian",
    "gender": "female",
    "age": "middle_aged",
    "useCase": "characters_animation",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/YIXhzp6l2M0ddzOGIbJ3/rnBT1BQBrdd0gBehPcUH.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "JT6473YSWOH0NkTbpbef",
    "name": "Shrey - Hindu Epic & Spiritual Narrator",
    "description": "Raw, grounded and deeply authentic \u2014 Shrey carries the natural gravitas of a storyteller who has lived with these texts, not just read them. His expressive Hindi delivery brings Hindu epics, Puranic tales, Ramayana, Mahabharata, and Bhagavad Gita teachings to life with the kind of spiritual weight that polished studio voices rarely achieve. Built for religious audiobooks, dharma podcasts, Hindu mythology series, devotional content, and spiritual learning platforms. ",
    "accent": "standard",
    "gender": "male",
    "age": "young",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/JT6473YSWOH0NkTbpbef/92Abe9XnifHSUuzoyURa.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "S80Lttx0YnvXrbhmEHVK",
    "name": "Jeet \u2013 Powerful Hindu Epic Voice",
    "description": "Jeet carries the power and gravitas that India's greatest epics demand. His commanding delivery brings legendary battles, divine heroes, and mythical feats to life \u2014 from the heroic journey of Rama to the dharma-driven war at Kurukshetra. Built for Ramayana narration, Mahabharata storytelling, and Hindu epic audiobook production \u2014 a natural fit for mythology content creators, Indian audiobook publishers, and YouTube channels building the next generation of epic Indian mythology content.\n\n",
    "accent": "standard",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/S80Lttx0YnvXrbhmEHVK/KqxxJpLXHuAprRRp2VUU.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "6EphsklDopDQ6eRkwNHT",
    "name": "Shardul K \u2013 Hindu Mythology Storyteller",
    "description": "Shardul K delivers a composed, immersive, and reverent storytelling style suited for Hindu mythology. His narration carries depth and gravitas, making epics feel authentic and engaging. Ideal for Ramayana and Mahabharata stories, Puranic tales, devotional content, spiritual explainers, and mythological storytelling. Perfect for YouTube mythology channels, audio series, devotional apps, podcasts, and educational platforms focused on Indian spiritual history.",
    "accent": "standard",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/6EphsklDopDQ6eRkwNHT/Dv9dEGDd7rgTIXmUmTaA.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "8f07fb5537cfc2afac034cd2b945ab222d549bb0292cfb2d932049faf993ee61",
    "voiceId": "idqMjIWpOlZ8jtr2hyYD",
    "name": "The Hindinator",
    "description": "They said it couldn't be done, WHOSE THEY.",
    "accent": "australian",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "conversational",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/user/NAKzDTDdYwakWaFsGz58jrolMEo1/voices/idqMjIWpOlZ8jtr2hyYD/a3bbafb9-2c30-4779-8d89-895691015e01.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "7b9mYhmnp0y2qSH1FnBL",
    "name": "Bunty - Funny Best Friend",
    "description": "Bunty\u2019s voice is full of charm, wit, and best-friend energy\u2014ideal for funny reels, roast-style rants, relatable meme content, and banter-led storytelling. With a naturally desi tone and perfect comic timing, his voice feels like your everyday buddy pulling your leg, making it perfect for creators, meme pages, and short-form comedy content on social media platforms.\n",
    "accent": "standard",
    "gender": "male",
    "age": "young",
    "useCase": "characters_animation",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/7b9mYhmnp0y2qSH1FnBL/zGkeBgS3uFAb0X28XrcH.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "f87f057c2250691953ac2e6227859706764bd08c88a055a18c74261957885a51",
    "voiceId": "vghiSqG5ezdhd8F3tKAD",
    "name": "Saira - Young influencer voice",
    "description": "Saira delivers an energetic, youthful, and engaging tone designed for modern social media storytelling. Her lively delivery captures attention quickly while keeping content fun, natural, and relatable. Ideal for reels, influencer content, lifestyle storytelling, brand collaborations, viral short-form videos, and creator-led social media campaigns where energy and personality drive audience engagement. Works especially well for fast-paced digital content and high-retention social media narration.",
    "accent": "standard",
    "gender": "female",
    "age": "young",
    "useCase": "social_media",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/514d94e9241c48e8b7905375729c436f/voices/vghiSqG5ezdhd8F3tKAD/FUiXiklM7yaALRuoP7yt.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "0UZ29F1kNDvmelKG8QCM",
    "name": "Raqib \u2013 Clear Documentary Presenter",
    "description": "Raqib delivers a clear, composed Hindi tone suited for documentary and factual presentation. His structured delivery keeps information precise and credible while maintaining engagement, making it ideal for host-led documentaries, investigative content, educational explainers, and historical narratives. Well-suited for Hindi content on platforms like Discovery Channels.",
    "accent": "standard",
    "gender": "male",
    "age": "young",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/0UZ29F1kNDvmelKG8QCM/102h8YSJjISkLBczp7Ul.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "vzov6y10x6nsGNFg883S",
    "name": "Samisha - Deep, Soft and Seductive",
    "description": "Samisha \u2013 Late Night Dramatic Storyteller for Audio Thrillers - A bold, immersive voice designed to build tension, mystery, and late-night intrigue in audio thrillers.\n\nSamisha\u2019s tone is rich, cinematic, and perfectly paced\u2014ideal for crime stories, psychological thrillers, supernatural fiction, and dark fantasy podcasts. Whether it\u2019s for Spotify, Audible, YouTube, or drama series narration apps, her voice pulls listeners in with every word, making twists and turns feel chillingly real.",
    "accent": "standard",
    "gender": "female",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/vzov6y10x6nsGNFg883S/CPEtRCVvJGCT1DhVXxW9.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "o6qTxWUeRyzRYZyUNDVJ",
    "name": "Irina \u2013 Energetic E-commerce Girl",
    "description": "Irina delivers an expressive, human-like, and youthful tone tailored for modern e-commerce interactions. Her energetic yet clear delivery keeps conversations engaging while maintaining structure and professionalism. Ideal for order confirmations, delivery updates, returns, product guidance, onboarding calls, and brand promotions. Well-suited for D2C,  online brands, and fast-growing digital brands.\n",
    "accent": "standard",
    "gender": "female",
    "age": "young",
    "useCase": "conversational",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/o6qTxWUeRyzRYZyUNDVJ/pHPQcw8SzJ9opK8BNCuR.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "f87f057c2250691953ac2e6227859706764bd08c88a055a18c74261957885a51",
    "voiceId": "SGbOfpm28edC83pZ9iGb",
    "name": "Ranbir - Calm, Steady and Clear",
    "description": "Ranbir M - Calm, Conversational Voice - A young and youthful voice, popularly used across genres. This tone and speaking style of the artist, has been extensively used for various narration projects on leading Indian platforms.",
    "accent": "standard",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "conversational",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/514d94e9241c48e8b7905375729c436f/voices/SGbOfpm28edC83pZ9iGb/jWFyUKnJjcFum9VO5mAu.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "K2Byg54sHB1oHegvENtI",
    "name": "Kanika - Calm & Commanding",
    "description": "Kanika delivers a calm yet commanding tone designed for structured recovery conversations. Her steady pacing reinforces authority without raising intensity, keeping payment discussions firm, clear, & compliance-focused. The delivery feels composed & decisive, making it effective for EMI reminders, overdue follow-ups, escalations, and resolution-driven collections. Well-suited for banks, lending institutions & fintech recovery operations.\n",
    "accent": "standard",
    "gender": "female",
    "age": "young",
    "useCase": "conversational",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/K2Byg54sHB1oHegvENtI/08uXEUVMPqnVNjMT0koY.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "BupS2QlyIIAUXuG8K2eb",
    "name": "Vedant - Smooth and Muffled",
    "description": "Vedant A - Smooth Narrative Voice - Many voices excel in narration or conversation, but very few are adept at both. This makes the voice a versatile, multipurpose asset, perfect for tasks ranging from dynamic narration to engaging conversational roles.\r\n\r\nIdeal for audiobooks, documentaries, commercials, voice-overs for films, interactive virtual assistants, and any project that demands both storytelling finesse and natural conversational flow.",
    "accent": "standard",
    "gender": "male",
    "age": "young",
    "useCase": "social_media",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/BupS2QlyIIAUXuG8K2eb/6oWSzuasq3lTWYRF1gPJ.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "3AMU7jXQuQa3oRvRqUmb",
    "name": "Viraj - Rich, Confident and Expressive",
    "description": "Viraj \u2013 Expressive & Natural Storyteller for Longform Audiobooks - Viraj delivers a richly modulated and emotionally expressive tone\u2014ideal for audiobooks and storytelling with vivid dialogue. His voice naturally shifts between characters, making it perfect for fiction, romance, thrillers, and mythology.\n\nThis profile is specially tuned for dialogue-heavy narration. With over 1.5 billion characters across his other profiles, Viraj is already one of the voice library\u2019 most celebrated voices.\n\nGreat fit for Audible, PocketFM, Spotify, KukuFM, & other longform platforms.",
    "accent": "standard",
    "gender": "male",
    "age": "young",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/3AMU7jXQuQa3oRvRqUmb/JoNum7jXo53rv5u7UP7f.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "lfQ3pGxnwOiKjnQKdwts",
    "name": "Meher - Deep, Suspenseful and Serious",
    "description": "Meher - Dramatic Female Narrator for Suspense, Horror & Mystery Tales - A gripping, expressive voice built to elevate dark fiction, chilling mysteries, and audio horror.\n\nMeher\u2019s delivery is intense yet controlled\u2014ideal for suspense thrillers, haunted tales, psychological drama, and mystery podcasts. Perfect for platforms like Audible, Spotify, YouTube, and fiction audio apps, her voice adds depth and drama that keeps listeners hooked till the final twist.",
    "accent": "standard",
    "gender": "female",
    "age": "young",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/lfQ3pGxnwOiKjnQKdwts/3yMPl7KGilzubstEZCHR.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "UbB19hYD8fvYxwJAVTY5",
    "name": "Anika \u2013 Expressive & High Energy ",
    "description": "Anika brings sweet, expressive, and high-energy hinglish delivery that instantly grabs attention. Her upbeat tone feels playful and engaging, making content feel exciting without becoming loud or harsh. She works especially well for viral reels, daily challenge formats, countdowns, hooks, and repeatable social concepts that rely on pace and clarity. A strong fit for short-form content on Instagram Reels, YouTube Shorts, and creator-led viral social campaigns.\n",
    "accent": "standard",
    "gender": "female",
    "age": "young",
    "useCase": "social_media",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/UbB19hYD8fvYxwJAVTY5/sAYqaN7loksEYjuDmpHH.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "dxhwlBCxCrnzRlP4wDeE",
    "name": "Arjun - Gentle Audiobook Narrator",
    "description": "Arjun - Gentle Narrator for Audiobooks and Educational Content - A soft-spoken and steady voice tailored for audiobooks, e-learning modules, and instructional videos.\n\nArjun\u2019s tone is calm, clear, and easy to follow \u2014 perfect for delivering long-form content that requires attention and retention. Whether it\u2019s a self-help book, academic guide, or educational explainer, his voice keeps the listener engaged without ever overwhelming.\n\nIdeal for Audible audiobooks, online courses, edtech apps, YouTube explainers, and guided learning content.",
    "accent": "standard",
    "gender": "male",
    "age": "young",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/dxhwlBCxCrnzRlP4wDeE/0na5TEuobTLNPitem1Bt.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "kvQSb3naDTi3sgHwwBC1",
    "name": "Monika Sogam \u2013 Deep and Clear",
    "description": " Monika Sogam \u2013 Smooth, Playful & Sexy Hindi Content Voice - Monika Sogam delivers a voice that\u2019s effortlessly smooth, flirtatious, and confidently bold. \n\nHer delivery strikes the right balance between sensual, playful, and expressive, making it an ideal fit for romantic stories, late-night talk content, character-driven voiceovers.\n\nWith over 3 billion characters generated across her profiles on the voice library, Monika stands as one of the most successful Hindi voices on the platform. ",
    "accent": "standard",
    "gender": "female",
    "age": "young",
    "useCase": "social_media",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/kvQSb3naDTi3sgHwwBC1/fVhpjaf9zKYWdXooFcRU.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "4BoDaQ6aygOP6fpsUmJe",
    "name": "Raghav - Calm, Confident and Engaging",
    "description": "Raghav - Calm & Confident Storyteller - A steady and composed voice crafted for storytelling, explainers, and thoughtful narration.\n\nRaghav\u2019s tone blends calm authority with warmth, making him perfect for delivering long-form content. Whether it\u2019s a brand story, podcast intro, or documentary narration, his voice keeps listeners engaged and at ease.\n\nIdeal for YouTube explainers, audiobooks, training videos, and informative reels across platforms like Spotify, Audible, and LinkedIn.",
    "accent": "standard",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/4BoDaQ6aygOP6fpsUmJe/N8hoKK2hY8Cxaf5RTeSl.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "CNKl99QEbWm8RQ4D8GfC",
    "name": "Chutki - Cute Young Kids Storyteller",
    "description": "Bubbly, sweet and impossible to tune out \u2014 Chutki brings the kind of cute, energetic storytelling that makes children lean in and listen. Her young, animated Hindi delivery brings bedtime stories, moral fables, Panchatantra tales, and kids audio adventures to life with a warmth and playfulness that feels like a best friend telling a story. Perfect for kids audio apps, bedtime story platforms, edtech content, and family storytelling channels.",
    "accent": "standard",
    "gender": "female",
    "age": "young",
    "useCase": "characters_animation",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/CNKl99QEbWm8RQ4D8GfC/xkQ6nHGxCvqKC5n25wEp.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "VZyYADHcMi33m0wO9zD1",
    "name": "Monika Sogam - Breathy and Suspenseful",
    "description": "Monika Sogam - Suspenseful & Engaging Narrator - Perfect for thrillers, crime podcasts, and suspenseful narrations.\r\n\r\nMonika Sogam's voice has captivated audiences on the voice library, with over 900 million characters generated. Due to popular demand, she's back\u2014this time, with a dataset crafted specifically for spine-chilling storytelling.",
    "accent": "standard",
    "gender": "female",
    "age": "young",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/VZyYADHcMi33m0wO9zD1/WD6sVMse7kVNZRa8e3Ce.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "7UUQ7nKkAFuNp9HpqSDh",
    "name": "Niraj - Serious, Compelling and Smooth",
    "description": "Niraj - Powerful, Modulated & Dramatic Narrator for Suspense Stories - Niraj\u2019s voice is dramatic and deeply modulated \u2014 ideal for suspenseful storytelling, thrillers, and intense narrations.\r\n\r\nAlready one of the most recognized narrator voices on the voice library with over 1 billion characters on his original profile, this new version leans even more into theatrical control and darker tones.\r\n\r\nPerfect for audio thrillers, horror podcasts, and dramatic content on platforms like Spotify, Kuku FM, Pratilipi FM, and YouTube Shorts.",
    "accent": "standard",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/7UUQ7nKkAFuNp9HpqSDh/T8eck0Y9i5OsKRWwMJSw.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "7398804d9eaf2f463899a907587c33a390591775784f87857b6d0e1e4e3e66f6",
    "voiceId": "qDuRKMlYmrm8trt5QyBn",
    "name": "Taksh - Calm, Serious and Smooth",
    "description": "Taksh - Powerful & Commanding Voice - Ideal voice for divine storytelling, historical epics, and philosophical reflections, this voice carries a deep, commanding presence\u2014rich in bass and authority, yet calm and deliberate. Perfect for epic narrations, mythology, and grand storytelling, it echoes wisdom and power. Every word feels profound, every sentence leaves an impact.",
    "accent": "standard",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/qDuRKMlYmrm8trt5QyBn/6jXyGArrGdTZLHE5Z0x1.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "d9ba38d6a0abb2bad207be033c951e0550cc6828c9fa74ff17235e7bc8d9be11",
    "voiceId": "wJ5MX7uuKXZwFqGdWM4N",
    "name": "Raj - Professional Indian English",
    "description": "Authentic Indian English accent with clear articulation and a professional, trustworthy tone. Versatile voice ideal for BFSI (Banking & Finance), Loan Journeys, and Sales Pitches. Optimized for Customer Support and Audio Agents (IVR/Call Centers) with a natural, conversational flow. Capable of warm storytelling for EdTech and seamless Hinglish delivery. High-quality studio recording perfect for corporate narration, explainers, and AI voice agents.",
    "accent": "indian",
    "gender": "male",
    "age": "young",
    "useCase": "conversational",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/2942f14150d2415e830b7bda5ae1c249/voices/wJ5MX7uuKXZwFqGdWM4N/JlFk4eRc9CdwXQauKX9B.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "6fd3438cdf34cd2cc8e2ef6f0d3bf7149d5a5c1606fb7f3069454edd279a1ad8",
    "voiceId": "txk8uOzZ0iCh0B9mFSRG",
    "name": "Rahul S \u2013 Natural Warm Indian English",
    "description": "Natural, warm, and highly conversational Indian English voice with a neutral global accent. Clear, articulate, and trustworthy - designed for AI products, modern brands, commercials, and professional storytelling. Delivers an authentic human feel that connects instantly.",
    "accent": "indian",
    "gender": "male",
    "age": "young",
    "useCase": "conversational",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/49bd6dfdb0d4421ea576d1ae6f24b2bd/voices/txk8uOzZ0iCh0B9mFSRG/jO50n68BVxDIculiPi8E.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "aba86dfe49af7fd6f81167054a2f52c39cd277ca01c5394b9f8d660d9dcdc6fb",
    "voiceId": "TmPeb2hSxdVrThJLywkg",
    "name": "Vanishree - Energetic Indian English",
    "description": "A young adult female with a clear contemporary urban Indian accent. Her delivery is professional and confident, ideal for business communications, technical explainers, reliable virtual assistants, corporate training modules, formal presentations, e-learning platforms, and news narration.",
    "accent": "indian",
    "gender": "female",
    "age": "young",
    "useCase": "informative_educational",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/user/SFyBesWA0qM3jCTNeNSiln4fMNs1/voices/TmPeb2hSxdVrThJLywkg/abefb106-24b3-4799-8005-220cea56ebbf.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "1d613473ce036ae5b3b1cc1f9bae94d547d6c62e6774eed3aad19fc212d70f3f",
    "voiceId": "NyZqLdjqUb8SpOUKIlWT",
    "name": "Sonal \u2013 Premium Indian English Voice",
    "description": "Sonal is a studio-grade female voice combining confident authority with natural warmth. Designed for enterprise use, she delivers polished narration ideal for AI agents, FinTech support, B2B SaaS, eLearning, and podcasts. Trained on 3.5+ hours of studio PVC data and optimized for Eleven v3 & Turbo v2.5, her neutral Indian-English accent ensures clear, expressive, low-latency delivery for global audiences.",
    "accent": "indian",
    "gender": "female",
    "age": "young",
    "useCase": "conversational",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/732fe2ac4bbe4281b2c1342d6aabdeb5/voices/NyZqLdjqUb8SpOUKIlWT/7epHiBagEHlPmbKrGQid.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "45ba03296b18bfbb2e660f46cdba05f50d96264d8ae5f15d14ace8c5f7e1a8fa",
    "voiceId": "SXuKWBhKoIoAHKlf6Gt3",
    "name": "Gaurav - Professional and Calm Indian English",
    "description": "Professional and Calm Indian English voice for voiceovers, podcasts and audiobooks. ",
    "accent": "indian",
    "gender": "male",
    "age": "young",
    "useCase": "informative_educational",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/user/vZWUr71Pf2SGtgKM7UbEYTiWM9z1/voices/SXuKWBhKoIoAHKlf6Gt3/9e5483c9-f49e-4145-b9f7-d16ce01f8709.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "27fcd87e88cc5e5aceae33e459f03040ffeb6f935b51006e0a2be474fae1e24a",
    "voiceId": "uavKGt8JpB2lo1bcty9J",
    "name": "Raj - Indian English Voice Agent",
    "description": "Raj is a calm Indian English male voice with a steady, reassuring, and trustworthy tone. Designed for AI voice agents, customer support, IVR, banking, fintech, insurance, telecom, e-commerce, healthcare, SaaS support, corporate training, product explainers, compliance messages, and professional narration, Raj delivers clear pronunciation, natural pacing, warm communication, and a composed business style.",
    "accent": "indian",
    "gender": "male",
    "age": "young",
    "useCase": "conversational",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/bd837480eefe40da9e9830363a89f264/voices/uavKGt8JpB2lo1bcty9J/7O0ZiYVQnrY5xdH9lgh5.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "fa87c5747e8cd32f6c90859a49a84ab09d07f006bc399199d1db8ee676238c5b",
    "voiceId": "MmiGAbOYCaIFzgNItUWa",
    "name": "Famous Indian Voice",
    "description": "Professional Indian male voice with a clear, confident tone and a neutral American-influenced accent. Perfect for YouTube narration, audiobooks, podcasts, commercials, explainer videos, e-learning courses, and corporate presentations. This voice offers smooth delivery, strong articulation, and a warm, engaging style that keeps listeners interested. Suitable for storytelling, educational content, motivational videos, advertisements, and digital media projects. ",
    "accent": "indian",
    "gender": "male",
    "age": "young",
    "useCase": "conversational",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/19bd272e13cd4c9dab539005291be985/voices/MmiGAbOYCaIFzgNItUWa/LE0cyi2HRk9IV1WoWnWm.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "fa5729446fbaf1e355f6134822ba6cd632d071c9b91243901708d7f67bad7285",
    "voiceId": "g19dpkfwlJXgbfszAJu4",
    "name": "Apsara - Podcast, Indian, Storytelling",
    "description": "Indian accent, narrative, storytelling. Mature voice for podcast, Indian voice-over.",
    "accent": "indian",
    "gender": "female",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/bd18ae76e9ad4077b764eb46fb22fdf5/voices/g19dpkfwlJXgbfszAJu4/daf4c3ca-5122-4154-ae47-e903561a8f14.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "b2722612b32b35ca670078542b27313120027f4879ad73e70c7dea4beb89f958",
    "voiceId": "mmSZflZFDoe6qEecRgIO",
    "name": "India - Husky & Cosmo",
    "description": "A deep, husky female voice with a modern, cosmopolitan Indian accent. Characterized by clear enunciation and a professional, rhythmic cadence. The tone is warm and grounded, avoiding high-pitched inflections, making it ideal for narration, presentations, or sophisticated AI agents.",
    "accent": "indian",
    "gender": "female",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/bb35e1900cfd4848ba11ec51fb2a659a/voices/mmSZflZFDoe6qEecRgIO/eaa4ba3d-e108-4a5c-a06c-b655fd477aba.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "c3b1b5cb2ad6440a8de52e61b7efd62f348a879c4cce74dabdae2e376e3f141c",
    "voiceId": "gYf9sqh3BkV9QqFMN9Hs",
    "name": "Anya - Neutral Indian Professional",
    "description": "A premium, studio-grade female voice featuring a neutral Indian English accent. This versatile voice bridges the gap between high-end studio narration and dynamic, real-time agentic conversations. With an articulate, warm, and trustworthy tone, it is the definitive choice for AI customer agents, interactive LLM personas, and voice-driven assistants. Beyond automation, its natural cadence excels in long-form podcasts, E-learning, and global marketing. Optimized for human-like conversational flow.",
    "accent": "indian",
    "gender": "female",
    "age": "young",
    "useCase": "conversational",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/8339042c4d3a4c60b4892a249563f569/voices/gYf9sqh3BkV9QqFMN9Hs/kpDN91hgcAOm6SKYcj7r.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "4c0fe820ddef2d3bc3c745db103abaf2b3b17e4b3c5bf7bc3fc2ad5af565abaf",
    "voiceId": "PSGmTr1P7xsA5H9W7obv",
    "name": "Balachander - South Indian Voice ",
    "description": "Expressive, sophisticated, happy, and articulate male voice.",
    "accent": "indian",
    "gender": "male",
    "age": "young",
    "useCase": "conversational",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/user/user_7701ke1fh9nke65rr34c3h7s4whe/voices/PSGmTr1P7xsA5H9W7obv/ad3610be-b4db-48e4-b690-a522b0483e6c.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "0b077b542d39f50369c69eebc1854c8033f7325a9cdc7ed10cc3894174593043",
    "voiceId": "AMYtAh0F0P3iH1uImfZh",
    "name": "Prince Jain -  Indian Multi-Accent Voice",
    "description": "Young Indian professional voice with a clear, confident tone and subtle neutral accent. Perfect for e-commerce product demos, social media reels. Warm, credible, and relatable for worldwide audiences ",
    "accent": "indian",
    "gender": "male",
    "age": "young",
    "useCase": "conversational",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/29a6c6929d294cb58f595bc9837ab6e5/voices/AMYtAh0F0P3iH1uImfZh/gzQA2XbpWrYu0TEMF8uw.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "0ca97729faff22ee3841f4eb985cd7e58e4a7687ba6d4afde460babdf249999d",
    "voiceId": "8WqHCYyrnUqoK70Px5EJ",
    "name": "Nitin - Indian Accent with emotions",
    "description": "A versatile voice designed to introduce your company across commercials, marketing campaigns, and social media platforms.",
    "accent": "indian",
    "gender": "male",
    "age": "young",
    "useCase": "conversational",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/924db83416dd4070b5bc85779d16fe15/voices/8WqHCYyrnUqoK70Px5EJ/89866b3a-0a1d-473a-98c4-b1d56a745269.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "87a31e26687e533d18305df39fde85f03077b068f556d6017a43973ace794704",
    "voiceId": "2W8HrWcBFzCEf5cQQdIL",
    "name": "Dark Indian Baritone Narrator",
    "description": "Deep male Indian voice for horror, documentary, storytelling, audiobooks, and trailers.",
    "accent": "indian",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "entertainment_tv",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/e5bfe039d3df4c5caee73869712096b3/voices/2W8HrWcBFzCEf5cQQdIL/abDUjwPTnzIohUzLPdOS.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "0095caaaf402dd7559e7c298c47fad1ba7e5af296bc37a8c07f1607a1ce4792f",
    "voiceId": "RpiHVNPKGBg7UmgmrKrN",
    "name": "Aashish - Natural Indian male",
    "description": "Natural and neutral male Indian accent with a warm tone and inspiring edge. Perfect for social media, medical explainers, internal corporate presentations and digital commercials.",
    "accent": "indian",
    "gender": "male",
    "age": "young",
    "useCase": "narrative_story",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/user/PuodI8YTQwV6MyatHUBvG6qXppZ2/voices/RpiHVNPKGBg7UmgmrKrN/GJFFf4KQFjJFi5vQkuYS.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "fda2169ba796e7b5c07eb8b74fa6d8a7df008ab92fefa473dda6b3d173a4ff7a",
    "voiceId": "01DQSLgg3WJX3GZ2K4fl",
    "name": "Ram - Indian with deep voice",
    "description": "Neutral and Professional.",
    "accent": "indian",
    "gender": "male",
    "age": "young",
    "useCase": "conversational",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/user/user_0601ke0w3t2zfjnbwcmc232rseac/voices/01DQSLgg3WJX3GZ2K4fl/bQHR0IJy1n1XJy793bXG.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "a9a45aadf0e5ec8bb426fe24c3be6a7e5a1cc0facfe5a7ec726dfdd7daece1b0",
    "voiceId": "cn9tQG5lDYsfG70MdIj0",
    "name": "Karthik - The south Indian voice",
    "description": "Middle-aged male voice for narration.",
    "accent": "indian",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "en",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/541e3c9cb29641d8895e4bd96004a325/voices/cn9tQG5lDYsfG70MdIj0/9442299e-f4e9-4d0a-b4b4-4b60482cdb30.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "e02b91958343b6cde28021bee45164f499c5e49b9a5968f215e912ff672ba2d1",
    "voiceId": "alJGMewmY1WX0fzByVd2",
    "name": "Tarun - Desi Indian Male Voice Pro",
    "description": "Young Indian male voice with a deep, confident, and naturally engaging tone. Perfect for Social Media videos, ads, reels, storytelling, and commercial projects. Delivers clear Hindi with real emotions \u2014 no robotic feel, just pure desi vibes. Modern urban style with studio-quality sound.",
    "accent": "standard",
    "gender": "male",
    "age": "young",
    "useCase": "social_media",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/workspace/774ba133e24147cebc206ce417393574/voices/alJGMewmY1WX0fzByVd2/jbe9AHyWFHSGdMsNxOUe.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "326f37a9625ca5b6d1409360454c16b56ca01c4c5bfb6ff5dec05619bd0fa347",
    "voiceId": "LQ2auZHpAQ9h4azztqMT",
    "name": "Parveen - Indian Male",
    "description": "This is the Indian Male voice of Parveen, which is perfect for the stories, podcast, and relaxing.",
    "accent": "standard",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "hi",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/user/xsdpAvuoNVdjFVUPPUeKOpHhAVO2/voices/LQ2auZHpAQ9h4azztqMT/88e831b6-95d4-4320-8b26-13755a69ce74.mp3",
    "category": "professional"
  },
  {
    "publicOwnerId": "e33eb547f8af39719b57253a6230915455d19c17d3f7781cabe273337a2e5df2",
    "voiceId": "k8cFOyAg7B9qwBlDDNTC",
    "name": "Miguel - Deep, Rich and Cinematic",
    "description": "Miguel - Commercials, Video games & Narration. - Miguel's deep, rich voice is reminiscent of famous movie trailers. His voice is currently one of the most prominent on social media worldwide.",
    "accent": "latin american",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "entertainment_tv",
    "language": "es",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/user/GJdoyaP8TaZz3yZHCWI2JwuCVsv1/voices/k8cFOyAg7B9qwBlDDNTC/KZqiLbg5cT5CZ7ANPaey.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "498dee577b9474794f17e268c852cb80fb7ae61d43ab43034a98c055ab3e30f3",
    "voiceId": "7VqWGAWwo2HMrylfKrcm",
    "name": "Fatih Y\u0131ld\u0131r\u0131m - Deep, Clear and Rich",
    "description": "Fatih Y\u0131ld\u0131r\u0131m - A young Turkish energetic male voice with a clear and dynamic tone , perfect for tutorials, tech reviews and engaging ,content slight warmth and confidence ideal for connecting with a broad audience. charismatic male voice , Ideal for documentaries and YouTube.",
    "accent": "istanbul",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "social_media",
    "language": "tr",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/user/OtUBACOPLZQxBWkdPFojsMctFZ93/voices/7VqWGAWwo2HMrylfKrcm/7282011b-0180-4ac0-8d75-8e87c7f2439d.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "495a061f9b7930e3c37627d5b711c6f999daccbb88f8b98d76ca5db18eaa98cd",
    "voiceId": "OlBp4oyr3FBAGEAtJOnU",
    "name": "Jora Slobod - Calm, Deep and Reassuring",
    "description": "Jora Slobod - A calm and low Romanian male voice, deep tone. Perfect for narratives, audiobooks, and general information.",
    "accent": "standard",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "ro",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/custom/voices/OlBp4oyr3FBAGEAtJOnU/Uub5cEzcyVo34vqgA9cA.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "e33eb547f8af39719b57253a6230915455d19c17d3f7781cabe273337a2e5df2",
    "voiceId": "UBXZKOKbt62aLQHhc1Jm",
    "name": "Fran\u00e7ois Louis - Deep, Warm and Poised",
    "description": "Fran\u00e7ois-Louis: A natural for French movies, commercials or narration of books - Middle-aged French male voice. Deep and resonant - perfect for narrations, social media and entertainment",
    "accent": "standard",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "fr",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/user/GJdoyaP8TaZz3yZHCWI2JwuCVsv1/voices/UBXZKOKbt62aLQHhc1Jm/aSlxrpg8s9ui1Nfe92hm.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "e7fea8016e07cbf918ca753255d7085b26536539ab23d1c18100164e2a920dfc",
    "voiceId": "v3V1d2rk6528UrLKRuy8",
    "name": "Susi - Effortless and Confident",
    "description": "Susi - Imagine the voice of the telemarketing assistant as soothing and melodic, with a clear, crisp tone that conveys both warmth and professionalism. Her speech is rhythmic and confident, effortlessly modulating to match the mood of the conversation. She possesses a subtle accent that adds a unique charm to her interactions, making her sound approachable and friendly. Her laughter is light and genuine, breaking into her speech naturally when the conversation allows.",
    "accent": "standard",
    "gender": "female",
    "age": "middle_aged",
    "useCase": "conversational",
    "language": "de",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/1KI0h0RJuscE0Ta9tVvydENJ9JF3/voices/v3V1d2rk6528UrLKRuy8/8aab3a1d-2faf-4de4-b229-f3a2ebb21c43.mp3",
    "category": "high_quality"
  },
  {
    "publicOwnerId": "54cfa52581962c6ef08b268db1d7748d105a7f19cd3b8dfff2d0fd42a19476c6",
    "voiceId": "QtPMrakdgePQIUwOX7Ut",
    "name": "Arconte - Evocative, Deep and Elegant",
    "description": "Arconte - Evocative & Magnetic - A deep voice from a professional mature voice actor that conveys confidence, intensity, and elegance. Perfect for storytelling, premium advertising, corporate narration, documentaries, trailers, and professional dubbing.\nA versatile raspy tone that brings credibility and a unique character to every project.",
    "accent": "peninsular",
    "gender": "male",
    "age": "middle_aged",
    "useCase": "narrative_story",
    "language": "es",
    "previewUrl": "https://storage.googleapis.com/eleven-public-prod/database/user/SwALNLfOnHOmkDaauO5ve4uctbm1/voices/QtPMrakdgePQIUwOX7Ut/9Vztpz5slLUeA7R86w4d.mp3",
    "category": "high_quality"
  }
] satisfies SharedVoiceSummary[];
